### ISSUE TITLE
Error : sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by fernandoneto** [Strider-CD/strider-docker-slave#5]
Hi,

I'm running strider-docker-slave, and all work great but in one of my repository i need to run a punch of commands from a `MAKEFILE` with sudo. He stops in the first command that have sudo.
The error is this.
`sudo: no tty present and no askpass program specified`
any suggestions how to fix this?
@niallo @jaredly 

Best regards

**Comment by mmathys** [comment]
just don't use sudo and it works.
